### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by matteosantama** [oz123/pytest-localftpserver#151]
## Test
```python
def test_test(ftpserver):
    assert True
```

## Pytest output
```
❯ pytest tests
=================================== test session starts ====================================
platform darwin -- Python 3.9.7, pytest-6.2.5, py-1.10.0, pluggy-1.0.0
rootdir: /Users/matteosantamaria/pathology
plugins: localftpserver-1.1.3
collected 1 item                                                                           

tests/test_path.py .                                                                 [100%]

===================================== warnings summary =====================================
tests/test_path.py::test_test
  /Users/matteosantamaria/.pyenv/versions/3.9.7/envs/pathology/lib/python3.9/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-1
  
  Traceback (most recent call last):
    File "/Users/matteosantamaria/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 973, in _bootstrap_inner
      self.run()
    File "/Users/matteosantamaria/.pyenv/versions/3.9.7/lib/python3.9/threading.py", line 910, in run
      self._target(*self._args, **self._kwargs)
    File "/Users/matteosantamaria/.pyenv/versions/3.9.7/envs/pathology/lib/python3.9/site-packages/pyftpdlib/servers.py", line 245, in serve_forever
      self.ioloop.loop(timeout, blocking)
    File "/Users/matteosantamaria/.pyenv/versions/3.9.7/envs/pathology/lib/python3.9/site-packages/pyftpdlib/ioloop.py", line 348, in loop
      poll(soonest_timeout)
    File "/Users/matteosantamaria/.pyenv/versions/3.9.7/envs/pathology/lib/python3.9/site-packages/pyftpdlib/ioloop.py", line 708, in poll
      kevents = self._kqueue.control(None, _len(self.socket_map),
  OSError: [Errno 9] Bad file descriptor
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================== 1 passed, 1 warning in 0.02s ===============================
```

## Versions
pytest: 6.2.5
pytest-localftpserver : 1.1.3
OS: macOS Big Sur 11.5.2
Python: 3.8, 3.9

It [looks](https://github.com/giampaolo/pyftpdlib/issues/526) like it has to do with being on `macOS`

**Comment by oz123** [comment]
This is a known issue with Mac OS X,
See; https://github.com/oz123/pytest-localftpserver/blob/dd24c6ea0a96113d97c92acfbdcc1938d9e310b5/pytest_localftpserver/servers.py#L1079

This allows you to step around this landmine.

**Comment by matteosantama** [comment]
Sorry, I'm not sure I follow. Are you suggesting that using a `ThreadFTPServer` should silence this warning? In the example

```python
def test_test(ftpserver):
    assert True
```

`ftpserver` is indeed of type `ThreadFTPServer`, and I still get the warning.

**Comment by oz123** [comment]
Yes, I was suggesting exactly that. Unfortunately, support
for os x is only on a best guess effort. I don't have any access to this os.

**Comment by matteosantama** [comment]
Fair enough. I'm not sure this issue should be closed then, as the problem persists. I will open an MR if I come up with a solution.
